---
# tasks file for win_package_install
 - name: Install OpenSSH
   win_chocolatey:
    name: "{{ item }}"
    params: "{{ parameters }}"
    state: latest
   with_items: "{{ package_name }}"
   when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
