---
# tasks file for win_ad_user
 - name: Create AD Users
   win_domain_user:
     name: "{{ item.name }}"
     firstname: "{{ item.firstname }}"
     surname: "{{ item.surname }}"
     password: "{{ item.password }}"
     state: present
     email: '"{{ item.name }}"@ad.c5aa.example.opentlc.com'
   with_items: "{{ user_info }}"
  

